name: Access app streamlit to keep it live

on:
  workflow_dispatch:

jobs:
  access_app:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install lib pandas
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Install lib selenium
      run: pip install selenium
    - name: Install lib requests
      run: pip install requests
    - name: Install lib bs4
      run: pip install bs4
      
    - name: app_imoveis
      run: |
          pwd;ls;python scrap-streamlit-imoveis.py
